apiVersion: apps/v1
kind: Deployment
metadata:
  name: commafeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commafeed
  template:
    metadata:
      labels:
        app: commafeed
    spec:
      securityContext:
        fsGroup: 33 # www-data group ID
        runAsUser: 33
        runAsGroup: 33
 
      securityContext:
            allowPrivilegeEscalation: false

      containers:
        - name: commafeed
          image: athou/commafeed:4.5.0
          
          ports:
            - containerPort: 8082
              protocol: TCP

          volumeMounts:
            - name: /commafeed/data
              name: commafeed-data
       
      volumes:
        - name: commafeed-data
          persistentVolumeClaim:
            claimName: commafeed-data

      restartPolicy: Always
